name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read version from package.json
          version=$(node -p "require('./package.json').version")
          version_tag="v$version"
          echo "Version from package.json: $version_tag"
          echo "version=$version_tag" >> $GITHUB_OUTPUT
          git tag $version_tag
          git push origin $version_tag

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create_tag.outputs.version }}
          name: Release ${{ steps.create_tag.outputs.version }}
          body: Automated release for version ${{ steps.create_tag.outputs.version }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
